src/Submissions.Web/Areas/Protrack/Models/MergeProjects/MergeProjects.cs
using Submissions.Web.Models.Query;
using System.Collections.Generic;

namespace Submissions.Web.Areas.Protrack.Models.Project
{
	public class MergeProjects
	{
		public MergeProjects()
		{
			Filters = new ProjectSearch();
		}
		public int ProjectId { get; set; }
		public string ProjectName { get; set; }
		public string ProjectStatus { get; set; }
		public bool IsTransfer { get; set; }

		public byte? BundleTypeId { get; set; }
		public ProjectSearch Filters { get; set; }
		public string MergeReason { get; set; }
		public List<MergeProject> SelProjectsToMerge { get; set; }

	}

	public class MergeProject
	{
		public int ProjectId { get; set; }
		public bool WithIndicator { get; set; }
		public bool IsTransfer { get; set; }
	}

	public class SearchResults
	{
		public int ProjectId { get; set; }
		public string ProjectName { get; set; }
		public string ReceivedDate { get; set; }
		public bool? IsTransfer { get; set; }
		public string Status { get; set; }
		public string Supervisor { get; set; }
		public byte? BundleTypeId { get; set; }
	}
}

src/Submissions.Web/Areas/Protrack/Controllers/MergeProjectsController.cs
using GLI.EFCore.Submission;
using Newtonsoft.Json;
using Submissions.Common;
using Submissions.Core;
using Submissions.Web.Areas.Protrack.Models.Project;
using Submissions.Web.Models.Query;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Submissions.Web.Areas.Protrack.Controllers
{
	public class MergeProjectsController : Controller
	{
		private readonly SubmissionContext _dbSubmission;
		private readonly IProjectService _projectService;
		private readonly IQueryService _queryService;

		public MergeProjectsController(SubmissionContext dbSubmission, IProjectService projectService, IQueryService queryService)
		{
			_dbSubmission = dbSubmission;
			_projectService = projectService;
			_queryService = queryService;
		}

		public ActionResult Index(int Id)
		{
			var vm = new MergeProjects();
			var projectInfo = _dbSubmission.trProjects.Where(x => x.Id == Id).Select(x => new { x.ProjectName, x.IsTransfer, ProjectStatus = x.ENStatus, x.BundleTypeId }).SingleOrDefault();
			vm.ProjectId = Id;
			vm.ProjectName = projectInfo.ProjectName;
			vm.ProjectStatus = projectInfo.ProjectStatus;
			vm.IsTransfer = (projectInfo.IsTransfer == true) ? true : false;
			vm.BundleTypeId = projectInfo.BundleTypeId;
			return View("Index", vm);
		}

		public JsonResult SearchProjects(int projectId, string filters)
		{
			var bundleTypeId = _dbSubmission.trProjects.Where(x => x.Id == projectId).Select(x => x.BundleTypeId).Single();
			var mergeFilters = JsonConvert.DeserializeObject<ProjectSearch>(filters);
			var query = _dbSubmission.trProjects.Where(x => x.Id != projectId && x.ENStatus != ProjectStatus.DN.ToString()).AsQueryable();

			if (!string.IsNullOrEmpty(mergeFilters.FileNumber))
			{
				query = query.Where(x => x.ProjectName.StartsWith(mergeFilters.FileNumber)).AsQueryable();
			}

			if (!string.IsNullOrEmpty(mergeFilters.Jurisdiction))
			{
				query = query.Where(x => x.JurisdictionalData.Any(y => y.JurisdictionalData.JurisdictionId == mergeFilters.Jurisdiction)).AsQueryable();
			}

			if (!string.IsNullOrEmpty(mergeFilters.ManufacturerShort))
			{
				query = query.Where(x => x.FileNumber.Contains(mergeFilters.ManufacturerShort)).AsQueryable();
			}

			var projects = query.Select(x => new SearchResults()
			{
				ProjectId = x.Id,
				ProjectName = x.ProjectName,
				Status = x.ENStatus,
				IsTransfer = x.IsTransfer,
				Supervisor = x.ENManager.FName + " " + x.ENManager.LName,
				BundleTypeId = x.BundleTypeId
			}).OrderBy(x => x.ProjectName).ToList();

			return Json((projects), JsonRequestBehavior.AllowGet);
		}

		public ActionResult IsMergeItemsFromSameFile(int origProjectId, int mergeWithId)
		{
			var itemsFromSameFile = "No";
			var whichOriginalProject = _dbSubmission.trProjects.Where(x => (x.Id == origProjectId || x.Id == mergeWithId)).Select(x => new { Id = x.Id, Name = x.ProjectName, IsTransfer = x.IsTransfer }).ToList();

			if (whichOriginalProject.Where(x => x.IsTransfer == false).Count() == 1)
			{
				var origProject = whichOriginalProject.Where(x => x.IsTransfer == false).Select(x => x.Name).FirstOrDefault();
				//check if all items from Transfer are from same file
				var transferProject = whichOriginalProject.Where(x => x.IsTransfer == true).Select(x => x.Id).FirstOrDefault();

				var itemsFromDiffFile = _dbSubmission.trProjectJurisdictionalData.Where(x => x.ProjectId == transferProject && x.JurisdictionalData.Submission.FileNumber != origProject).Any();
				itemsFromSameFile = (itemsFromDiffFile) ? "No" : "Yes";
			}

			return Content(itemsFromSameFile);
		}

		public ActionResult IsProjectHasBilledHours(int projectId)
		{
			var results = _queryService.ProjectUnassignedTaskHours(projectId).ToList();
			var TotalActualAssigned = results.Where(x => x.IsAssigned == true).ToList().Sum(x => x.Hours);

			return Content((TotalActualAssigned > 0) ? "Yes" : "No");
		}

		public ContentResult Save(MergeProjects vm, string SelProjectsToMerge)
		{
			var projectId = 0;
			var selMergeProjects = JsonConvert.DeserializeObject<List<MergeProject>>(SelProjectsToMerge);
			//check if any selected is a new submission, then Merge orig transfer into New submission
			if (vm.IsTransfer == true && (selMergeProjects.Where(x => x.IsTransfer == false && x.WithIndicator == false).Any()))
			{
				projectId = selMergeProjects.Where(x => x.IsTransfer == false && x.WithIndicator == false).Select(x => x.ProjectId).FirstOrDefault();
			}
			else
			{
				projectId = vm.ProjectId;
			}

			foreach (var project in selMergeProjects)
			{
				var projectInfo = _dbSubmission.trProjects.Where(x => x.Id == project.ProjectId).Select(x => new { x.BundleTypeId, x.MergedWith }).SingleOrDefault();
				if (vm.BundleTypeId != projectInfo.BundleTypeId)
				{
					project.WithIndicator = true;
				}

				if (project.ProjectId == projectId)//Merge Transfer into selected New submission
				{
					_projectService.MergeProjects(projectId, vm.ProjectId, vm.MergeReason, project.WithIndicator);
				}
				else
				{
					_projectService.MergeProjects(projectId, project.ProjectId, vm.MergeReason, project.WithIndicator);
				}
			}
			return Content(projectId.ToString());
		}

		public ActionResult UnMerge(int projectId, int mergeProjectId)
		{
			_projectService.UnMerge(projectId, mergeProjectId);
			return RedirectToAction("Detail", "Project", new { Id = projectId });
		}
	}
}

src/Submissions.Web/Areas/Protrack/Views/MergeProjects/Index.cshtml
@model Submissions.Web.Areas.Protrack.Models.Project.MergeProjects

@section css{
	 <style>
	   
	</style>
}
@{
	ViewBag.Title = "Merge Project ";
}

<div class="row">
	<div class="col-sm-6">
		<h3 class="form-h3">@ViewBag.Title To - <small>@Model.ProjectName (ProjectStatus - @Model.ProjectStatus)</small></h3>
	</div>
	<div class="col-sm-6 form-buttons text-right">

		@if (Model.ProjectStatus != ProjectStatus.DN.ToString()) {
		<input type="button" id="MergeBtn" class="btn btn-primary btn-sm" value="Merge Project" onclick="">
		}
		<input type="reset" id="CancelBtn" class="btn btn-primary btn-sm" value="Cancel" onclick="window.parent.location.reload();window.close()">
	</div>
</div>

@using (Html.BeginForm("Save", "MergeProjects", FormMethod.Post, new { MergeProjectModel = Model, Id = "MergeProjectForm" }))
{
@Html.HiddenFor(x => x.ProjectId)
@Html.HiddenFor(x => x.IsTransfer)
@Html.HiddenFor(x => x.BundleTypeId)
@Html.Hidden("SelProjectsToMerge")

	   <div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Search Projects</h3>
			</div>
			<div class="panel-body">
				<div class="form-horizontal">
					<div class="row">
						<div class="col-sm-3">
							<div class="form-group form-group-sm">
								@Html.LabelFor(m => m.Filters.FileNumber, new { @class = "control-label col-sm-4" })
								<div class="col-sm-8">
									@Html.TextBoxFor(m => m.Filters.FileNumber, "", new { @class = "form-control" })
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="form-group form-group-sm">
								@Html.LabelFor(m => m.Filters.ManufacturerShort, new { @class = "control-label col-sm-4" })
								<div class="col-sm-8">
									@Html.LookupFor(m => m.Filters.ManufacturerShort, m => m.Filters.Manufacturer, LookupAjax.Manufacturers, false)
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="form-group form-group-sm">
								@Html.LabelFor(m => m.Filters.Jurisdiction, new { @class = "control-label col-sm-4" })
								<div class="col-sm-8">
									@Html.LookupFor(m => m.Filters.Jurisdiction, m => m.Filters.JurisdictionDesc, LookupAjax.Jurisdictions, false)
								</div>
							</div>
						</div>
						<div class="col-sm-1">
							<div class="form-group form-group-sm">
								<button type="button" class="btn btn-primary" id="Search"><i class="fas fa-search"></i>&nbsp;Search</button>
							</div>
						</div>
					</div>
				 </div>
			</div>
		</div>
	<br />
		<div id="SearchResults" style="display: none">
			 <div class="row">
				<div class="form-group col-sm-7">
					<label>Select Project to Merge:</label>
					<div id="DivResults" style="overflow-y:auto">
						<table id="ProjectSearchResults" class="table table-condensed">
							<thead>
								<tr>
									<th></th>
									<th>Project Name</th>
									<th>Status</th>
									<th>Supervisor</th>
								</tr>
							</thead>
							<tbody id="ProjectSearchList"></tbody>
						</table>
					</div>
				</div>
				<div class="form-group col-sm-5">
					<label>Merge Reason:</label>
					@Html.TextAreaFor(model => model.MergeReason, 3, 60, new { @class = "form-control", @placeholder = "Enter Merge Reason" })
				</div>
			   
			</div>
		</div>
}
<!--if Project has Dynamic hours-->

<div class="modal fade" id="ShowMergeOptions" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header text-right">
				<button type="button" class="btn btn-primary" id="MergeOptionsBtn" onclick="return false;">Merge Project</button>
				<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<label class="form-control-label bg-warning" id="MergeOptionMsg"></label><br />
					<label class="form-control-label">Do you really want to merge and remove selected project(s)?</label>
					&nbsp;<input type="radio" id=MergeOptions name="MergeOptions" value='Yes'>&nbsp;Yes&nbsp; &nbsp; &nbsp;<input type="radio" id=MergeOptions name="MergeOptions" value='No'>&nbsp;No
					<br><br><p>Selecting <code>'Yes'</code> will remove selected project(s) and merge items into @Model.ProjectName.<br>Selecting <code>'No'</code> will keep selected project and merge will be shown by an indicator on Project Detail page.  </p>
					<br />
				</div>
			</div>
		</div>
	</div>
</div>

 @section scripts{
<script>
			$(function () {
				document.getElementById('Filters_FileNumber').addEventListener('keypress', function (event) {
					if (event.keyCode == 13) {
						event.preventDefault();
					}
				});

				$('#Search').click(function () {
					if (Em($('#Filters_FileNumber').val()) && Em($('#Filters_Jurisdiction').val()) && Em($('#Filters_ManufacturerShort').val())) {
						bootbox.alert("Please enter search criteria.");
					}
					else {
						SearchProjects();
					}
				});

				var affectedIds = [];
				function addAffectedId(Id, isTransfer, isIndicator) {
					
					var affectedObject = {};
						affectedObject.ProjectId = Id;
						affectedObject.WithIndicator = isIndicator;
						affectedObject.IsTransfer = isTransfer
						affectedIds.push(affectedObject);
				}

				$('#MergeOptionsBtn').click(function () {
					if ($('input[Id=MergeOptions]:radio:checked').val() == undefined) {
						bootbox.alert("Please select Yes or No.");
					}
					else {
						
						if ($('input[Id=MergeOptions]:radio:checked').val() == 'Yes') {
							//by default it is set as false in object
						}
						else {
						
							for (var i = 0; i < affectedIds.length; i++) {
								if (affectedIds[i].IsTransfer == "true") {
									affectedIds[i].WithIndicator = "True"
								}
							}
						}
						$('#SelProjectsToMerge').val(JSON.stringify(affectedIds));
						$('#MergeProjectForm').submit();

					}

				});


				$('#MergeBtn').click(function () {
					var ProjectsWithDynamicsHours = false;
					var isProjectSelected = false;
					var showOptionsWin = false;
					var msg = '';

					$('input[Id=selProject]').each(function () {

						var isChecked = (this.checked ? "1" : "0");
						if (isChecked == 1) {
							isProjectSelected = true;
							var selProjectId = $(this).val().split(",")[0]
							var SelIsTransfer = $(this).val().split(",")[1]
							var bundleTypeId = $(this).val().split(",")[2]

							
							if ($('#BundleTypeId').val() == bundleTypeId) { // if same bundleTypeId or else with indicator
								//If one is new submission and second is Transfer
								//Check if selected both have same file jurisdictions
								if ($('#IsTransfer').val() == "True" && SelIsTransfer == "true") {
									//dont do anything
								}
								else {
									var isItemsOkToMerge = checkIfBothProjectHasSameFileItems($('#ProjectId').val(), selProjectId)
								}
								if (isItemsOkToMerge || ($('#IsTransfer').val() == "True" && SelIsTransfer == "true")) // if  both projects are transfers
								{
									//Check if acct has hours
									if (CheckIfHoursAssigned(selProjectId)) {
										ProjectsWithDynamicsHours = true
									}
									showOptionsWin = true;
									addAffectedId(selProjectId, SelIsTransfer, "False")
								} else {
									addAffectedId(selProjectId, SelIsTransfer, "True")
								}
							}
							else {
								addAffectedId(selProjectId, SelIsTransfer, "True")
							}
						}
					})

					if (isProjectSelected == false) {
						msg = "Please select project to Merge<br>"
					}

					if (Em($('#MergeReason').val())) {
						msg += "Please enter Merge Reason.";
					}

					if (!Em(msg)) {
						bootbox.alert(msg)
					}
					else {
						if (showOptionsWin) {
							if (ProjectsWithDynamicsHours) {
								$('#MergeOptionMsg').text('There are hours in dynamics for selected project(s).')
							}
							$('#ShowMergeOptions').modal('show');
						}
						else {
							$('#SelProjectsToMerge').val(JSON.stringify(affectedIds));
							$('#MergeProjectForm').submit();
						}
					}

				})

				//$('#MergeBtn').click(function () {
				//    var msg = ""
				//    if ($('input[Id=selProject]:radio:checked').val() == undefined) {
				//        msg = "Please select project to Merge<br>"
				//    }
				//    if (Em($('#MergeReason').val())) {
				//        msg += "Please enter Merge Reason.";
				//    }
				//    if (!Em(msg))
				//    {
				//        bootbox.alert(msg)
				//    }
				//    else
				//    {
				//        var selProjectId = $('input[Id=selProject]:radio:checked').val().split(",")[0]
				//        var SelIsTransfer = $('input[Id=selProject]:radio:checked').val().split(",")[1]

				//        $('#MergeProjectId').val(selProjectId)
				//        if ($('#IsTransfer').val() == "True" && SelIsTransfer == "true") // if  both projects are transfers
				//        {
				//            //Check if acct has hours
				//           if (CheckIfHoursAssigned(selProjectId)) {
				//                $('#MergeOptionMsg').text('There are hours in dynamics for this project.')
				//                $('#ShowMergeOptions').modal('show');
				//           }
				//           else {
				//                $('#ShowMergeOptions').modal('show');
				//           }

				//        } else {
				//            $('#MergeWithIndicator').val("True")
				//            $('#MergeProjectForm').submit();
				//        }

				//    }
				//});
			});


			function checkIfBothProjectHasSameFileItems(origProjectId, mergeWithId) {
				var url = '@Url.Action("IsMergeItemsFromSameFile", "MergeProjects")?origProjectId=' + origProjectId + "&mergeWithId=" + mergeWithId
				var result = false
				$.ajax({
					url: url,
					async: false,
					success: function (data) {
						if (data == "Yes") {
							result = true;
						}
						else {
							result = false;
						}
					}
				});
				return result;
			}

			function CheckIfHoursAssigned(selId) {

				var url = '@Url.Action("IsProjectHasBilledHours", "MergeProjects")?projectId=' + selId
				var result = false
				$.ajax({
					url: url,
					async: false,
					success: function (data) {
						if (data == "Yes") {
							result = true;
						}
						else {
							result = false;
						}
					}
				});
				return result;
			}

			function SearchProjects() {
				var filters = {}
				filters.FileNumber = $('#Filters_FileNumber').val()
				filters.ManufacturerShort = $('#Filters_ManufacturerShort').val();
				filters.Jurisdiction = $('#Filters_Jurisdiction').val();
				var sfilters = JSON.stringify(filters)
				var url = '@Url.Action("SearchProjects", "MergeProjects")?projectid=' + $('#ProjectId').val() + '&filters=' + sfilters

				$.getJSON(url, null, function (data) {
					$('#ProjectSearchList').html('')
					if (data.length > 0) {
						for (x = 0; x < data.length; x++) {
							$('#ProjectSearchList').append('<tr><td><input type=checkbox id=selProject name=selProject value="' + data[x].ProjectId + ',' + data[x].IsTransfer + ',' + data[x].BundleTypeId  + '"></td><td>' + data[x].ProjectName + '</td><td>' + data[x].Status + '</td><td>' + data[x].Supervisor + '</td></tr>');
						}
					}
				});
				$('#SearchResults').show();

				//so user dont have to scroll if they do search my manuf or jur.
				var containerHeight = $(window).height();
				var padding = 300;
				$("#DivResults").height(containerHeight-padding);

			}

			$('#MergeProjectForm').submit(function () {

				var openProjectId = 0
				$.ajax({
					url: this.action,
					type: this.method,
					async: false,
					data: $(this).serialize(),
					success: function (result) {
						if (result != "")
						{
							openProjectId = result
						}
						
					}
				});
				//only on prod getting Internal server error. putting it here
				alert("Projects were merged successfully.")
				if (openProjectId == $('#ProjectId').val()) {
					window.opener.location.reload();
				}
				else {
					if (openProjectId > 0) {
						var url = '@Url.Action("Detail", "Project")' + '/' + openProjectId
						window.opener.location.href = url;
					}
					
				}
				window.close();
				return false;
			});

</script>
 }