src/Submissions.Web/Areas/Protrack/Models/ComplexityRating/ComplexityRating.cs
using System.ComponentModel;

namespace Submissions.Web.Areas.Protrack.Models.Project
{
	public class ComplexityRating
	{
		[DisplayName("Complexity Rating:")]
		public int? ComplexityRatingId { get; set; }
		public string ComplexityRatingDesc { get; set; }

		[DisplayName("Product Type:")]
		public int? ProductTypeId { get; set; }
		public string ProductTypeDesc { get; set; }
		public int LoginId { get; set; }
		public string FileNumber { get; set; }
		public string ProjectIds { get; set; }
	}
}

src/Submissions.Web/Areas/Protrack/Controllers/ComplexityRatingController.cs
using GLI.EFCore.Submission;
using Submissions.Core;
using Submissions.Web.Areas.Protrack.Models.Project;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Submissions.Web.Areas.Protrack.Controllers
{
	public class ComplexityRatingController : Controller
	{
		private readonly IProjectService _projectService;
		private readonly SubmissionContext _dbSubmission;

		public ComplexityRatingController(IProjectService projectService, SubmissionContext submissionContext)
		{
			_projectService = projectService;
			_dbSubmission = submissionContext;
		}

		//
		// GET: /Protrack/ComplexityRating/
		public ActionResult Index(int projectId)
		{
			var vm = new ComplexityRating();
			vm.ProjectIds = projectId.ToString();
			var projectFileNumber = _dbSubmission.trProjects.Where(x => x.Id == projectId).Select(x => x.FileNumber).Single();
			var item = _dbSubmission.FileNumberComplexityRating.Where(x => x.FileNumber == projectFileNumber).SingleOrDefault();
			if (item != null)
			{
				vm.ComplexityRatingId = item.ComplexityRatingId;
				vm.ProductTypeId = item.ProductTypeId;
			}
			return PartialView("_ComplexityRating", vm);
		}

		public ActionResult BatchComplexityRating(string projectIds)
		{
			var vm = new ComplexityRating();
			vm.ProjectIds = projectIds;
			return PartialView("_ComplexityRating", vm);
		}

		public JsonResult SaveComplexityRating(ComplexityRating vm)
		{
			var listProjects = new List<int>(vm.ProjectIds.Split(',').Select(x => int.Parse(x)));
			if (listProjects.Count > 0)
			{
				for (int i = 0; i < listProjects.Count; i++)
				{
					_projectService.UpdateProjectComplexityRating(listProjects[i], (int)vm.ProductTypeId, (int)((vm.ComplexityRatingId == null) ? 0 : vm.ComplexityRatingId));
				}
			}

			var results = (from p in _dbSubmission.trProjects
						   join f in _dbSubmission.FileNumberComplexityRating on p.ProjectName equals f.FileNumber
						   where listProjects.Contains(p.Id)
						   select (new { ProjectId = p.Id, NewVal = _dbSubmission.tbl_lst_ComplexityRating.Where(x => x.Id == f.ComplexityRatingId).Select(x => x.Rating).FirstOrDefault() })).ToList();

			return Json(results, JsonRequestBehavior.AllowGet);

		}

		public JsonResult ManufacturerRequiresComplexityRating(string projectIds)
		{
			var allResponse = "";
			var listProjects = new List<int>(projectIds.Split(',').Select(x => int.Parse(x)));
			if (listProjects.Count > 0)
			{
				var manufCodeList = (from p in _dbSubmission.trProjects
									 join s in _dbSubmission.SubmissionHeaders on p.FileNumber equals s.FileNumber
									 where listProjects.Contains(p.Id)
									 select s.ManufacturerCode).Distinct().ToList();

				for (int i = 0; i < manufCodeList.Count; i++)
				{
					var manufCode = manufCodeList[i];
					var response = _projectService.ManufacturerRequiresComplexityRating(manufCode);
					if (response)
					{
						if (allResponse == "")
						{
							allResponse = manufCode;
						}
						else
						{
							allResponse += "," + manufCode;
						}

					}
				}
			}

			return Json(allResponse, JsonRequestBehavior.AllowGet);
		}
	}
}

src/Submissions.Web/Areas/Protrack/Views/ComplexityRating/_ComplexityRating.cshtml
@model Submissions.Web.Areas.Protrack.Models.Project.ComplexityRating
@{
    ViewBag.NoNavBar = true;
    ViewBag.NoFooter = true;
}
<style>

</style>
@{
    ViewBag.Title = "Product Complexity Rating";
}
@using (Html.BeginForm("SaveComplexityRating", "ComplexityRating", FormMethod.Post, new { complexityRatingVM = Model, Id = "ComplexityForm" }))
{
    @Html.HiddenFor(m => m.ProjectIds);
    <div class="modal-header">
        <div class="row">
            <div class="col-sm-12 form-buttons text-right">
                <button type="button" id="Save" accesskey="C" class="btn btn-primary btn-sm"><i class="fas fa-save"></i>&nbsp;Save (Alt+C)</button>
                <button class="btn btn-primary btn-sm" data-dismiss="modal" aria-hidden="true">Close</button>
            </div>
        </div>
    </div>
    <div class="modal-body">
        <div class="container-fluid">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Complexity Rating Information</h3>
                    </div>
                    <label id="Error" class="text-danger"></label>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            <div class="form-group form-group-sm">
                                @Html.LabelFor(model => model.ProductTypeId, new { @class = "control-label col-sm-4" })
								<div class="col-sm-8">
									@Html.LookupFor(m => m.ProductTypeId, m => m.ProductTypeDesc, LookupAjax.ProductTypes,true)
									<br />
								</div>
                            </div>
                            <div class="form-group form-group-sm">
                                @Html.LabelFor(model => model.ComplexityRatingId, new { @class = "control-label col-sm-4" })
								<div class="col-sm-8">
									@Html.LookupFor(m => m.ComplexityRatingId, m => m.ComplexityRatingDesc, LookupAjax.ComplexityRating, true)
								</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
    <script>
    $(function () {
        loadDocumentReady();
        $('#Save').click(function () {
            var Error = ''

            if ($('#ProductTypeId').val() == "") {
                Error += 'You must select Product Type.'
            }
            else if ($('#ComplexityRatingId').val() == "") {
                 Error += checkManuf()
            }

            if (Error == '') {
                $('#ComplexityForm').submit();
            }
            else {
                $('#Error').text(Error);
                return false;
            }
        });


        $('#ComplexityForm').submit(function () {

            $('#Save').prop("disabled", true);
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    if ("@Request["OnlyRefreshValues"]" == 1)
                    {
                        $('#myModal').modal('toggle');
                        ReSetUpdatedValuesAfterSave("Complexity", result);
                        bootbox.alert("Data updated.")
                    }
                    else {
                            window.location.reload();
                    }
                }
            });

            return false;
        });

        function checkManuf() {
            var ret = "0"
            var url = '@Url.Action("ManufacturerRequiresComplexityRating", "ComplexityRating")?projectIds=' + $("#ProjectIds").val();
            $.ajax({
                url: url,
                async: false,
                success: function (data) {
                    if (data != "") {
                        ret = 'You must select Complexity Rating for ' + data + "."
                    }
                    else {
                        ret = ""
                    }
                }
            });
            return ret;
        }
    });
    </script>